#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: BSD-3-Clause
# Copyright (C) 2026 Petr Wozniak (WOZIWRT project)
# Start mesh-gwd, the daemon that keeps the internet gateway on whichever
# node holds the ISP cable. Disabled by default: enable it only once the
# clients' gateway is the VIP, otherwise it just adds a spare address.
START=98
STOP=10
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/mesh-gwd
	procd_set_param respawn 3600 5 0
	procd_set_param stderr 1
	procd_close_instance
}
